### ISSUE TITLE
本地调试调试起来之后不下载PDB

### ISSUE THREAD

**Issue by lsz7575** [sonyps5201314/pdb#2]
虚拟机系统 win7 6.1    7601  sp1
调试起来,Modules窗口 -> ntdll.dll 鼠标右键 ->  Load debug symbols 就弹出错误 

错误信息如下
ntdll.dll: failed to load pdb info
不支持此接口
Do you want to browse for the pdb file on disk?

我测试了,没有替换的原版是可以下载pdb的..替换之后就不下载了
ida是我从52pojie上下的,版本是Version 7.5.201028 Windows x64 (32-bit address size)

**Comment by sonyps5201314** [comment]
![录像1_转](https://user-images.githubusercontent.com/20564099/117855879-84b5c480-b2bd-11eb-8a58-ca0b5cb38c50.gif)
我这里测试正常的啊，怀疑是你那里对微软符号服务器的网络暂时出现问题。

**Comment by sonyps5201314** [comment]
或者是符号缓存文件夹存在损坏的ntdll.pdb文件，建议你清空符号缓存目录再试。

**Comment by lsz7575** [comment]
> ![录像1_转](https://user-images.githubusercontent.com/20564099/117855879-84b5c480-b2bd-11eb-8a58-ca0b5cb38c50.gif)
> 我这里测试正常的啊，怀疑是你那里对微软符号服务器的网络暂时出现问题。

win10 我也可以哦... win7 6.1 7601 sp1 不工作,      :)
非常抱歉回得这么慢,我不太会用github.

**Comment by sonyps5201314** [comment]
最新版本已经修复了，如果你这台电脑还是不行，请安装好最新的系统补丁再试，因为symsrv.dll及msdia140.dll对一些系统组件的版本有要求。

**Comment by lsz7575** [comment]
> 最新版本已经修复了，如果你这台电脑还是不行，请安装好最新的系统补丁再试，因为symsrv.dll及msdia140.dll对一些系统组件的版本有要求。

可以了,非常感谢老哥..
