### ISSUE TITLE
Include issues

### ISSUE THREAD

**Issue by greenozon** [sonyps5201314/pdb#3]
include links like
#include "../../ldr/pe/pe.h"
are hardly resolved
any better way?

**Comment by sonyps5201314** [comment]
cd 'your IDASDK directory'\plugins
git clone https://github.com/sonyps5201314/pdb pdb_mod
open pdb_mod\pdb_vs201x.sln for build.

**Comment by greenozon** [comment]
Agree, i t works in this case
but if you try to build up pdb plugin in a separate dir outside IDA SDK it'll fail to resolve paths

**Comment by sonyps5201314** [comment]
you can modify vs INCLUDE value to include your IDA SDK include for the separate dir situation.

**Comment by greenozon** [comment]
Yeah, agree!
the only confusing thing is that you need to add 2 paths to IDA SDK, not one!
one for include subdir to resolve heades like #include <fpro.h>
and another dir to resolve 
#include "../../ldr/pe/pe.h"

Good luck! 
closing
thanks for you work
